spring:
  application:
    name: tongzhou
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tongzhou
    username: root
    password: ysq666666
  # session失效时间
  session:
    timeout: 86400

server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    # 开启SQL日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    edu.scut.tongzhou: info